### PR TITLE
Hello Microverse

### PR DESCRIPTION
**Pull request by Gmanlove**
### **On this pull request the following requirements were made**

- [ ] I set up linter configurations.
- [ ] I ignored node modules.
- [ ] I created an Html Hello Microverse with Css styling.
- [ ] I modified REAME.md file to properly describe the project.

### CODE REVIEW

**Review by Gopxfs — CHANGES_REQUESTED** [review]
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi @Gmanlove 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights :rocket:
✔️ No linter errors.
✔️ Great folder structure. Well done!
✔️ Perfect PR summary.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gopxfs** [comment]
Hello @Gmanlove, your readme is looking professional, but it can be improved 😉. To do so: 
- [ ] Please only add the live demo link if your project has one 😉:
image

- [ ] Kindly avoid empty sections: 
image

- [ ] [OPTIONAL] Nice job adding the corresponding link to your social media! I recommend that you change the link name from `githubhandle` to your name: 
image 
e.g. Github: [Gmanlove]()

- [ ] Please change `Author 1` to your name, and make sure to remove the `Author 2` template 😄:
image

- [ ] Make sure to only add links to the social media that you use. Currently, the Twitter and LinkedIn links are broken.

- [ ] Make sure to add the corresponding path to your MIT since it isn't working: :wink:: 
image

**Comment by Gopxfs** [comment]
Great job with your first Pull Request! Your folder structure looks great and the PR information is direct and clear 😉. Keep up the good work!

**Review by GedeonTS — APPROVED** [review]
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @Gmanlove ,

Your are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

 

## Highlights :clap: :tophat: 
- No linter errors :+1: 
- Good use of Github flow :+1: 
- gitignore is working fine :+1: 
## Optional suggestions :small_airplane: 
- [ OPTIONAL ] Good jo starting your commits with a capital letter :+1: , I think it would be better to write them in the imperative form, describing what change you just made. because it would make your project look more professional
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
